### PR TITLE
fix(collection-view): heading aligment to the center

### LINKED ISSUE #1825: Messages in CollectionView align to left
### Problem

I believe it is a simple problem to solve. When I tried to customize the messages in the collection view component, all the texts were aligned to the left.

Captura de Tela 2024-08-15 às 17 54 55

### Expected behavior

Centralize the texts

### PR DESCRIPTION
**Pull request by viniciuslagedo**
## Summary
Resolves #1825 

## Examples

```typescript
<CollectionView
  status="empty"
  messages={{
    'empty-heading':
      'No products created inside this category yet.',
    'empty-description': 'Use the button below to create a new product',
    'empty-action': 'Create product',
  }}
  onEmpty={() => alert('On empty action')}
>
  <div className="ready-view" />
</CollectionView>

```

Captura de Tela 2024-08-22 às 14 19 51

### CODE REVIEW

File: packages/shoreline/src/components/collection/collection-view.tsx [hunk 1]
```diff
@@ -74,7 +74,12 @@ export const CollectionView = forwardRef<HTMLDivElement, CollectionViewProps>(
           <EmptyStateIllustration data-sl-collection-view-illustration>
             {getIcon(status)}
           </EmptyStateIllustration>
-          <Heading data-sl-collection-view-heading>{heading}</Heading>
+          <Heading
+            data-sl-collection-view-heading
+            style={{ textAlign: 'center' }}
```
Comment (lucasaarcoverde) [inline packages/shoreline/src/components/collection/collection-view.tsx:79]: you should add this style to the `collection-view.css` [theme file](https://github.com/vtex/shoreline/blob/main/packages/shoreline/src/themes/sunrise/components/collection-view.css)

Something like that:
```css
[data-sl-collection-view-heading] {
  text-align: center;
}
```

**Review by lucasaarcoverde — CHANGES_REQUESTED** [review]

File: packages/shoreline/src/components/collection/collection-view.tsx (hunk 1 above)
Comment (viniciuslagedo) [reply packages/shoreline/src/components/collection/collection-view.tsx:79]: Uuuh! Good to know about this file <3

**Review by lucasaarcoverde — APPROVED** [review]
Thanks for your contribution! ✨
